# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: true

jdk:
- openjdk13

services:
- postgresql

# before_install:
#  - psql -c 'create database cars;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="d9a39a7f-3d70-468c-a195-29ce8a8d9dcd"

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка   упала
notifications:
  email:
    recipients:
      - telesyn73@mail.ru
    on_success: never # default: change
    on_failure: never # default: always
